export * from './comment/comment.component';
export * from './posts/posts.component';
export * from './post/post.component';
export * from './comments/comments.component';
export * from './user/user.component';
export * from './users/users.component';
export * from './user-details/user-details.component';
export * from './post-details/post-details.component';
export * from './comment-details/comment-details.component';
